"""
Gap Analysis Schema
====================
Pydantic model representing structured insights comparing resume details with job specifications.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class GapAnalysis(BaseModel):
    """Structured gap analysis between the candidate's resume and job requirements."""

    matching_skills: list[str] = Field(
        default_factory=list,
        description="List of skills that exist in both the resume and the job requirements.",
    )
    missing_skills: list[str] = Field(
        default_factory=list,
        description="List of required skills in the job specification that are not found in the resume.",
    )
    improvement_recommendations: list[str] = Field(
        default_factory=list,
        description="Actionable advice generated by the Gap Analyst to refine and optimize the application.",
    )
